Rename

diff --git a/initsystem/shutdown b/initsystem/shutdown
--- a/initsystem/shutdown
+++ b/initsystem/shutdown
@@ -1,6 +1,6 @@
 #!/usr/bin/ash
 
-# This file is part of initd
+# This file is part of initsystem
 #
 # Copyright (C) 2014 Valère Monseur (valere dot monseur at ymail dot com)
 #
@@ -20,24 +20,36 @@
 
 set -u
 
-PATH="/sbin:/bin:/usr/sbin:/usr/bin"
+PATH="/opt/busybox"
 export PATH
-
-cd /
-umask 0
 
 ################################################################################
 # sanity check #################################################################
 ################################################################################
 
-if [ $$ != 1 ]; then
-  echo "error: this script should be pid 1"
+if [ $(id -u) != 0 ]; then
+  echo "error: this script should be run as root"
   exit 1
 fi
 
 ################################################################################
-# pid 1 ########################################################################
+# shutdown #####################################################################
 ################################################################################
 
-exec /usr/bin/initd \
-  "/opt/busybox/getty -l /opt/busybox/login 38400 tty2 linux"
+case `basename $0` in
+  halt)
+    kill -12 1 # SIGUSR2
+    ;;
+  poweroff)
+    kill -15 1 # SIGTERM
+    ;;
+  reboot)
+    kill -10 1 # SIGUSR1
+    ;;
+  *)
+    echo "usage: halt|poweroff|reboot"
+    exit 1
+    ;;
+esac
+
+exit 0
