rework initramfs

diff --git a/initramfs/initramfs b/initramfs/initramfs
--- a/initramfs/initramfs
+++ b/initramfs/initramfs
@@ -2,7 +2,7 @@
 
 # This file is part of initsystem
 #
-# Copyright (C) 2014-2016 Valère Monseur (valere dot monseur at ymail dot com)
+# Copyright (C) 2014-2017 Valère Monseur (valere dot monseur at ymail dot com)
 #
 # This program is free software; you can redistribute it and/or modify
 # it under the terms of the GNU General Public License as published by
@@ -18,10 +18,8 @@
 # with this program; if not, write to the Free Software Foundation, Inc.,
 # 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
 
-PATH=/sbin:/bin:/usr/sbin:/usr/bin
-LC_ALL=C
-
-export PATH LC_ALL
+export PATH=/bin:/sbin:/usr/bin:/usr/sbin
+export LC_ALL=C
 
 cd /
 umask 022
@@ -40,10 +38,10 @@ fi
 ################################################################################
 
 reboot_system() {
-  echo "initramfs: rebooting in 7 seconds"
+  echo "initramfs: rebooting in 10 seconds"
 
-  killall5 -TERM; sleep 4
-  killall5 -KILL; sleep 3
+  killall5 -TERM; sleep 5
+  killall5 -KILL; sleep 5
 
   umount -a -r
   reboot -f
@@ -52,15 +50,39 @@ reboot_system() {
 rescue_shell() {
   echo "initramfs: loading keymap"
 
-  if [ -f /etc/keymap ]; then
-    loadkmap < /etc/keymap
-  fi
+  loadkmap < /etc/keymap
 
   echo "initramfs: dropping to rescue shell"
-  echo "initramfs: 'setsid cttyhack sh' to get a controlling terminal"
+  echo "initramfs: type 'setsid cttyhack ash' to get a controlling terminal"
+  echo "initramfs: type 'exit' to reboot the system"
 
   sulogin /dev/console
   reboot_system
+}
+
+wait_filesystem() {
+  for i in $(seq $2); do
+    if [ -e "$(findfs "$1")" ]; then
+      return
+    fi
+
+    sleep .25
+  done
+
+  echo "initramfs: timeout reached"
+  rescue_shell
+}
+
+check_fsck() {
+  if [ $(( $1 & 2 )) -eq 2 ]; then
+    echo "initramfs: system will be rebooted due to fsck error(s) $1"
+    reboot_system
+  fi
+
+  if [ $(( $1 | 33 )) -ne 33 ]; then
+    echo "initramfs: fsck error(s) $1"
+    rescue_shell
+  fi
 }
 
 ################################################################################
@@ -93,26 +115,19 @@ for COMMAND in $(cat /proc/cmdline); do
       INIT="${COMMAND#init=}"
       ;;
     root=*)
+      # root=/dev/xxx or root=UUID=xxx or root=LABEL=xxx
       ROOT="${COMMAND#root=}"
-      ;;
-    rootfstype=*)
-      TYPE="${COMMAND#rootfstype=}"
       ;;
   esac
 done
 
 if [ -z "${INIT}" ]; then
-  echo "initramfs: using default /sbin/init"
+  echo "initramfs: using default init=/sbin/init"
   INIT="/sbin/init"
 fi
 
 if [ -z "${ROOT}" ]; then
-  echo "initramfs: missing root=the_device (e.g. /dev/sda1) on kernel command line"
-  rescue_shell
-fi
-
-if [ -z "${TYPE}" ]; then
-  echo "initramfs: missing rootfstype=the_filesystem_type (e.g. ext4) on kernel command line"
+  echo "initramfs: missing root filesystem"
   rescue_shell
 fi
 
@@ -130,11 +145,9 @@ hwclock -t -u
 
 echo "initramfs: loading modules"
 
-if [ -f /etc/modules ]; then
-  while IFS= read -r MODULE; do
-    modprobe "${MODULE}"
-  done < /etc/modules
-fi
+while IFS= read -r MODULE; do
+  modprobe "${MODULE}"
+done < /etc/modules
 
 ################################################################################
 # pre-mount break ##############################################################
@@ -149,50 +162,27 @@ fi
 # filesystems ##################################################################
 ################################################################################
 
-wait_filesystem() {
-  for i in $(seq $2); do
-    if [ -e "$1" ]; then
-      return 0
-    fi
-
-    sleep .25
-  done
-
-  return 1
-}
-
-echo "initramfs: waiting for root filesystem"
+echo "initramfs: waiting for root filesystem ${ROOT}"
 
 wait_filesystem "${ROOT}" 240
 
-if [ $? -ne 0 ]; then
-  echo "initramfs: timeout reached for ${ROOT}"
-  rescue_shell
-fi
+ROOT="$(findfs "${ROOT}")" # get the filesystem device
+eval $(blkid "${ROOT}" | awk '{print $NF}') # get the filesystem type
 
-echo "initramfs: checking root filesystem"
+echo "initramfs: checking root filesystem ${ROOT} (${TYPE})"
 
 touch /etc/fstab
 ln -s /proc/self/mounts /etc/mtab
 
-fsck -T -t "${TYPE}" "${ROOT}"; STATUS=$?
-
-if [ $STATUS -ne 0 ] && [ $STATUS -ne 1 ] && [ $STATUS -ne 32 ]; then
-  echo "initramfs: fsck error ${STATUS} encountered on ${ROOT}"
-
-  if [ $STATUS -eq 2 ]; then
-    reboot_system
-  fi
-
-  rescue_shell
-fi
+fsck -T -t "${TYPE}" "${ROOT}"
+check_fsck $?
 
 echo "initramfs: mounting root filesystem read-only"
 
 mount -r -t "${TYPE}" "${ROOT}" /newroot
 
 if [ $? -ne 0 ]; then
-  echo "initramfs: cannot mount ${ROOT} with type ${TYPE}"
+  echo "initramfs: cannot mount root filesystem"
   rescue_shell
 fi
 
@@ -200,17 +190,8 @@ echo "initramfs: checking other filesystems"
 
 cp -f /newroot/etc/fstab /etc/fstab
 
-fsck -T -A -R; STATUS=$?
-
-if [ $STATUS -ne 0 ] && [ $STATUS -ne 1 ] && [ $STATUS -ne 32 ]; then
-  echo "initramfs: fsck error ${STATUS} encountered"
-
-  if [ $STATUS -eq 2 ]; then
-    reboot_system
-  fi
-
-  rescue_shell
-fi
+fsck -T -A -R
+check_fsck $?
 
 ################################################################################
 # post-mount break #############################################################
@@ -225,10 +206,10 @@ fi
 # init #########################################################################
 ################################################################################
 
-echo "initramfs: checking init"
+echo "initramfs: checking init program ${INIT}"
 
 if [ ! -x /newroot/"${INIT}" ]; then
-  echo "initramfs: init program ${INIT} doesn't exist or is not executable"
+  echo "initramfs: init program doesn't exist or is not executable"
   rescue_shell
 fi
 
@@ -253,6 +234,6 @@ echo "initramfs: switching root filesystem"
 
 exec env -i /bin/switch_root /newroot "${INIT}"
 
-echo "initramfs: cannot switch to /newroot and execute ${INIT}"
+echo "initramfs: cannot switch root filesystem and execute init program"
 
 rescue_shell
diff --git a/initramfs/mkinitramfs b/initramfs/mkinitramfs
--- a/initramfs/mkinitramfs
+++ b/initramfs/mkinitramfs
@@ -2,7 +2,7 @@
 
 # This file is part of initsystem
 #
-# Copyright (C) 2014-2016 Valère Monseur (valere dot monseur at ymail dot com)
+# Copyright (C) 2014-2017 Valère Monseur (valere dot monseur at ymail dot com)
 #
 # This program is free software; you can redistribute it and/or modify
 # it under the terms of the GNU General Public License as published by
@@ -22,29 +22,32 @@
 # gunzip initramfs-linux.cpio.gz
 # busybox cpio -i -d -H newc -F initramfs-linux.cpio
 
-PATH=/opt/busybox
-LC_ALL=C
+export PATH=/opt/busybox
+export LC_ALL=C
 
-export PATH LC_ALL
 umask 022
+
+################################################################################
+# sanity check #################################################################
+################################################################################
+
+if [ $(id -u) -ne 0 ]; then
+  echo "mkinitramfs: this script should be run as root"
+  exit 1
+fi
 
 ################################################################################
 # parameters ###################################################################
 ################################################################################
 
-if [ $(id -u) -ne 0 ]; then
-  echo "error: this script should be run as root"
-  exit 1
-fi
-
 LINUX="$1"
 
 if [ ! -e /etc/mkinitcpio.d/"${LINUX}".preset ]; then
-  echo "error: $1 is not a .preset file in /etc/mkinitcpio.d/"
+  echo "mkinitramfs: ${LINUX} is not a .preset file in /etc/mkinitcpio.d/"
   exit 1
 fi
 
-echo ">>> generating initramfs-${LINUX}.cpio.gz <<<"
+echo ">>> generating /boot/initramfs-${LINUX}.cpio.gz <<<"
 
 ################################################################################
 # base directory ###############################################################
@@ -52,7 +55,12 @@ echo ">>> generating initramfs-${LINUX}.cpio.gz <<<"
 
 echo "mkinitramfs: creating temporary base directory"
 
-BASE=$(mktemp -d /tmp/initramfs.XXXXXX)
+BASE="$(mktemp -d /tmp/initramfs.XXXXXX)"
+
+if [ $? -ne 0 ]; then
+  echo "mkinitramfs: cannot create temporary base directory"
+  exit 1
+fi
 
 trap 'rm -rf "${BASE}"; echo "mkinitramfs: an error has occurred, aborting!"; exit 1' INT TERM EXIT
 
@@ -68,12 +76,12 @@ for DIRECTORY in bin dev etc etc/modprobe.d lib lib64 mnt newroot proc root \
 done
 
 ################################################################################
-# etc ##########################################################################
+# configuration files ##########################################################
 ################################################################################
 
 echo "mkinitramfs: installing configuration files"
 
-echo "root:x:0:0:root:/root:/bin/sh" > "${BASE}"/etc/passwd
+echo "root:x:0:0:root:/root:/bin/ash" > "${BASE}"/etc/passwd
 
 echo "root:x:0:root" > "${BASE}"/etc/group
 echo "tty:x:5:" >> "${BASE}"/etc/group
@@ -109,22 +117,24 @@ done
 echo "mkinitramfs: installing dynamically linked binaries"
 
 add_binary() {
-  if [ ! -e "${BASE}/$1" ]; then
-    install -D "$1" "${BASE}/$1"
+  FILE="$(readlink -f "$1")"
+
+  if [ ! -e "${BASE}/${FILE}" ]; then
+    install -D "${FILE}" "${BASE}/${FILE}"
   fi
 
-  if [ "$1" != "$2" ]; then
-    if [ ! -L "${BASE}/$2" ]; then
-      ln -s "$1" "${BASE}/$2"
+  if [ "${FILE}" != "$1" ]; then
+    if [ ! -L "${BASE}/$1" ]; then
+      ln -s "${FILE}" "${BASE}/$1"
     fi
   fi
 }
 
 add_binaries() {
-  add_binary "$(readlink -f "$1")" "$1"
+  add_binary "$1"
 
   for BINARY in $(/usr/bin/ldd "$1" | grep -v "linux-vdso.so.1" | awk '{print $(NF-1)}'); do
-    add_binary "$(readlink -f "${BINARY}")" "${BINARY}"
+    add_binary "${BINARY}"
   done
 }
 
@@ -138,16 +148,17 @@ done
 # modules and firmwares ########################################################
 ################################################################################
 
-echo "mkinitramfs: installing kernel modules and firmwares"
+VERSION="$(/usr/bin/lsinitramfs /boot/initramfs-"${LINUX}".img | grep -m 1 "usr/lib/modules/" | awk -F / '{print $4}')"
+
+echo "mkinitramfs: installing kernel modules and firmwares ($VERSION)"
 
 add_module() {
-  REGEXP=$(basename "$1" | sed 's/[-_]/[\\-_]/g')
-  MODULES=$(grep "/${REGEXP}.*:" "/usr/lib/modules/${VERSION}/modules.dep")
+  REGEXP="$(basename "$1" | sed 's/[-_]/[\\-_]/g')"
+  MODULES="$(grep "/${REGEXP}.*:" "/usr/lib/modules/${VERSION}/modules.dep" | tr -d ':')"
 
   for MODULE in $MODULES; do
-    MODULE="${MODULE%:}"
     install -D -m644 "/usr/lib/modules/${VERSION}/${MODULE}" "${BASE}/lib/modules/${VERSION}/${MODULE}"
-    basename "${MODULE}" .ko.gz >> "${BASE}"/etc/modules
+    basename "${MODULE}" >> "${BASE}"/etc/modules
   done
 }
 
@@ -157,19 +168,18 @@ add_firmware() {
   fi
 }
 
-VERSION=$(/usr/bin/lsinitramfs /boot/initramfs-"${LINUX}".img | grep -m 1 "usr/lib/modules/" | awk -F / '{print $4}')
-
 for FILE in $(/usr/bin/lsinitramfs /boot/initramfs-"${LINUX}".img); do
   case "${FILE}" in
-    "usr/lib/modules/"*.ko) add_module "${FILE}" ;;
+    "usr/lib/modules/"*.ko*) add_module "${FILE}" ;;
     "usr/lib/firmware/"*) add_firmware "${FILE#usr}" ;;
   esac
 done
 
+sed -i '/^\s*$/d' "${BASE}"/etc/modules
 depmod -b "${BASE}" "${VERSION}"
 
 for OPTION in /etc/modprobe.d/*.conf /lib/modprobe.d/*.conf; do
-  install -D -m644 "${OPTION}" "${BASE}"/etc/modprobe.d
+  install -m644 "${OPTION}" "${BASE}"/etc/modprobe.d
 done
 
 ################################################################################
