rework initramfs, upgrade dbus

diff --git a/initramfs/mkinitramfs b/initramfs/mkinitramfs
--- a/initramfs/mkinitramfs
+++ b/initramfs/mkinitramfs
@@ -2,7 +2,7 @@
 
 # This file is part of initsystem
 #
-# Copyright (C) 2014-2015 Valère Monseur (valere dot monseur at ymail dot com)
+# Copyright (C) 2014-2016 Valère Monseur (valere dot monseur at ymail dot com)
 #
 # This program is free software; you can redistribute it and/or modify
 # it under the terms of the GNU General Public License as published by
@@ -23,6 +23,10 @@
 # busybox cpio -i -d -H newc -F initramfs-linux.cpio
 
 PATH=/opt/busybox
+LC_ALL=C
+
+export PATH LC_ALL
+umask 022
 
 ################################################################################
 # parameters ###################################################################
@@ -36,7 +40,7 @@ fi
 LINUX="$1"
 
 if [ ! -e /etc/mkinitcpio.d/"${LINUX}".preset ]; then
-  echo "error: parameter is not a .preset file in /etc/mkinitcpio.d"
+  echo "error: $1 is not a .preset file in /etc/mkinitcpio.d/"
   exit 1
 fi
 
@@ -50,7 +54,7 @@ echo "mkinitramfs: creating temporary base directory"
 
 BASE=`mktemp -d /tmp/initramfs.XXXXXX`
 
-trap 'rm -rf "${BASE}"; echo "mkinitramfs: an error occured, stopping!"; exit 1' INT TERM EXIT
+trap 'rm -rf "${BASE}"; echo "mkinitramfs: an error has occurred, aborting!"; exit 1' INT TERM EXIT
 
 ################################################################################
 # directory structure ##########################################################
@@ -58,9 +62,9 @@ trap 'rm -rf "${BASE}"; echo "mkinitramfs: an error occured, stopping!"; exit 1'
 
 echo "mkinitramfs: installing directory structure"
 
-for DIR in bin dev etc lib lib64 mnt newroot proc root run sbin sys tmp usr \
-           usr/bin usr/lib usr/lib64 usr/sbin var; do
-  install -d -m755 "${BASE}"/"${DIR}"
+for DIRECTORY in bin dev etc etc/modprobe.d lib lib64 mnt newroot proc root \
+                 run sbin sys tmp usr usr/bin usr/lib usr/lib64 usr/sbin var; do
+  install -d -m755 "${BASE}/${DIRECTORY}"
 done
 
 ################################################################################
@@ -80,8 +84,8 @@ umask 022
 
 dumpkmap > "${BASE}"/etc/keymap
 
-install -D -m644 /dev/null "${BASE}"/etc/ld.so.conf
-install -D -m644 /etc/localtime "${BASE}"/etc/localtime
+install -m644 /dev/null "${BASE}"/etc/ld.so.conf
+install -m644 /etc/localtime "${BASE}"/etc/localtime
 
 ################################################################################
 # statically linked binaries ###################################################
@@ -89,12 +93,12 @@ install -D -m644 /etc/localtime "${BASE}"/etc/localtime
 
 echo "mkinitramfs: installing statically linked binaries"
 
-install -D -m755 /usr/bin/busybox "${BASE}"/usr/bin/busybox
-install -D -m4755 /usr/bin/busybox-suid "${BASE}"/usr/bin/busybox-suid
+install -m755 /usr/bin/busybox "${BASE}"/usr/bin/busybox
+install -m4755 /usr/bin/busybox-suid "${BASE}"/usr/bin/busybox-suid
 
 for BINARY in /usr/bin/busybox /usr/bin/busybox-suid; do
-  for APPLET in `"${BASE}"/"${BINARY}" --list`; do
-    ln -s "${BINARY}" "${BASE}"/bin/"${APPLET}"
+  for APPLET in `"${BASE}/${BINARY}" --list`; do
+    ln -s "${BINARY}" "${BASE}/bin/${APPLET}"
   done
 done
 
@@ -104,103 +108,69 @@ done
 
 echo "mkinitramfs: installing dynamically linked binaries"
 
-add_one_binary() {
-  OBINARY="$1"
-  RBINARY=`readlink -f "${OBINARY}"`
-
-  if [ ! -e "${BASE}"/"${RBINARY}" ]; then
-    install -D "${RBINARY}" "${BASE}"/"${RBINARY}"
+add_binary() {
+  if [ ! -e "${BASE}/$1" ]; then
+    install -D "$1" "${BASE}/$1"
   fi
 
-  if [ "${OBINARY}" != "${RBINARY}" ]; then
-    if [ ! -L "${BASE}"/"${OBINARY}" ]; then
-      ln -s "${RBINARY}" "${BASE}"/"${OBINARY}"
+  if [ "$1" != "$2" ]; then
+    if [ ! -L "${BASE}/$2" ]; then
+      ln -s "$1" "${BASE}/$2"
     fi
   fi
 }
 
-add_all_binary() {
-  add_one_binary "$1"
+add_binaries() {
+  add_binary `readlink -f "$1"` "$1"
 
-  for BINARY in `/usr/bin/ldd "$1" | grep -v linux-vdso.so.1 | sed 's/.*=>//' | sed 's/(0x.*//'`; do
-    add_one_binary "${BINARY}"
+  for BINARY in `/usr/bin/ldd "$1" | grep -v "linux-vdso.so.1" | awk '{print $(NF-1)}'`; do
+    add_binary `readlink -f "${BINARY}"` "${BINARY}"
   done
 }
 
 for FILESYSTEM in ext2 ext3 ext4 fat vfat msdos; do
-  add_all_binary /usr/bin/fsck."${FILESYSTEM}"
+  add_binaries /usr/bin/fsck."${FILESYSTEM}"
 done
 
 /usr/bin/ldconfig -r "${BASE}" -f /etc/ld.so.conf -C /etc/ld.so.cache
 
 ################################################################################
-# modules ######################################################################
+# modules and firmwares ########################################################
 ################################################################################
 
-echo "mkinitramfs: installing kernel modules"
+echo "mkinitramfs: installing kernel modules and firmwares"
 
 add_module() {
-  # build regexp to find module
-  MOD_EXP=/`echo "$1" | sed 's/[-_]/[\\-_]/g'`.ko.gz
+  REGEXP=`basename "$1" | sed 's/[-_]/[\\-_]/g'`
+  MODULES=`grep "/${REGEXP}.*:" "/usr/lib/modules/${VERSION}/modules.dep"`
 
-  # find module in package files
-  MOD_PTH=`grep "${MOD_EXP}" "${MOD_PKG}"`
-
-  # module not found
-  if [ -z "${MOD_PTH}" ]; then
-    echo "error: module $1 not found"
-    return 1
-  fi
-
-  # install module in initramfs
-  install -D -m644 /"${MOD_PTH}" "${BASE}"/"${MOD_PTH#usr}"
-
-  if [ $# -eq 1 ]; then
-    basename "${MOD_PTH}" .ko.gz >> "${BASE}"/etc/modules
-  fi
-
-  # find module dependencies
-  MOD_DEP=`grep "${MOD_EXP}": /usr/lib/modules/"${MOD_VER}"/modules.dep | cut -d ':' -f 2`
-
-  for MOD_NAM in `echo "${MOD_DEP}"`; do
-    # find dependency name
-    MOD_NAM=`basename "${MOD_NAM}" .ko.gz`
-
-    # recursively add every dependency
-    add_module "${MOD_NAM}" "$1"
+  for MODULE in $MODULES; do
+    MODULE="${MODULE%:}"
+    install -D -m644 "/usr/lib/modules/${VERSION}/${MODULE}" "${BASE}/lib/modules/${VERSION}/${MODULE}"
+    basename "${MODULE}" .ko.gz >> "${BASE}"/etc/modules
   done
 }
 
-if [ -r /etc/mkinitramfs.d/"${LINUX}".module ]; then
-  MOD_PKG=`ls -d /var/lib/pacman/local/${LINUX}-[0-9].*`/files
-  MOD_VER=`grep 'modules.dep$' "${MOD_PKG}" | awk -F/ '{print $(NF-1)}'`
+add_firmware() {
+  if [ ! -d "$1" ]; then
+    install -D "$1" "${BASE}/$1"
+  fi
+}
 
-  grep -E -v "^[[:blank:]]*(#|$)" /etc/mkinitramfs.d/"${LINUX}".module | while read MODULE; do
-    add_module "${MODULE}"
-  done
+VERSION=`/usr/bin/lsinitramfs /boot/initramfs-"${LINUX}".img | grep -m 1 "usr/lib/modules/" | awk -F / '{print $4}'`
 
-  depmod -b "${BASE}" "${MOD_VER}"
+for FILE in `/usr/bin/lsinitramfs /boot/initramfs-"${LINUX}".img`; do
+  case "${FILE}" in
+    "usr/lib/modules/"*.ko) add_module "${FILE}" ;;
+    "usr/lib/firmware/"*) add_firmware "${FILE#usr}" ;;
+  esac
+done
 
-  for MOD_OPT in /etc/modprobe.d/*; do
-    install -D -m644 "${MOD_OPT}" "${BASE}"/"${MOD_OPT}"
-  done
-else
-  echo "error: /etc/mkinitramfs.d/${LINUX}.module doesn't exist or is not readable"
-fi
+depmod -b "${BASE}" "${VERSION}"
 
-################################################################################
-# firmwares ####################################################################
-################################################################################
-
-echo "mkinitramfs: installing firmwares"
-
-if [ -r /etc/mkinitramfs.d/"${LINUX}".firmware ]; then
-  grep -E -v "^[[:blank:]]*(#|$)" /etc/mkinitramfs.d/"${LINUX}".firmware | while read FIRMWARE; do
-    install -D "${FIRMWARE}" "${BASE}"/"${FIRMWARE}"
-  done
-else
-  echo "error: /etc/mkinitramfs.d/${LINUX}.firmware doesn't exist or is not readable"
-fi
+for OPTION in /etc/modprobe.d/*.conf /lib/modprobe.d/*.conf; do
+  install -D -m644 "${OPTION}" "${BASE}"/etc/modprobe.d
+done
 
 ################################################################################
 # initscript ###################################################################
@@ -208,7 +178,7 @@ fi
 
 echo "mkinitramfs: installing initscript"
 
-install -D -m755 /usr/lib/initramfs/initramfs "${BASE}"/init
+install -m755 /usr/lib/initramfs/initramfs "${BASE}"/init
 
 ################################################################################
 # initramfs ####################################################################
@@ -219,22 +189,21 @@ echo "mkinitramfs: generating initramfs archive"
 cd "${BASE}"
 
 umask 077
-find . | cpio -o -H newc | gzip > ../initramfs-"${LINUX}".cpio.gz
+find . | cpio -o -H newc | gzip > /tmp/initramfs-"${LINUX}".cpio.gz
 umask 022
-
-echo "mkinitramfs: installing initramfs archive"
 
 cd ..
 
-install -D -m600 initramfs-"${LINUX}".cpio.gz /boot/initramfs-"${LINUX}".cpio.gz
+echo "mkinitramfs: installing initramfs archive"
 
-echo "mkinitramfs: cleaning temporary base directory"
+install -m600 /tmp/initramfs-"${LINUX}".cpio.gz /boot/initramfs-"${LINUX}".cpio.gz
 
-rm -f initramfs-"${LINUX}".cpio.gz
+echo "mkinitramfs: cleaning temporary files"
+
+rm -f /tmp/initramfs-"${LINUX}".cpio.gz
 rm -rf "${BASE}"
 
 echo ">>> generation done <<<"
 
 trap - INT TERM EXIT
-
 exit 0
