rework all status functions and rewrite rc bin script

diff --git a/services/rc b/services/rc
--- a/services/rc
+++ b/services/rc
@@ -29,68 +29,66 @@ BLUE="\e[1;34m"
 MAGENTA="\e[1;35m"
 
 rc_status() {
-  if [ $# -gt 1 ]; then
-    rc_usage
-    return 1
-  fi
 
-  if [ -x /usr/bin/udevd ]; then
-    SERVICES="${SERVICES} eudev"
-  fi
+  shift
 
-  if [ -x /usr/lib/systemd/systemd-udevd ]; then
-    SERVICES="${SERVICES} udev"
-  fi
+  [ -x /usr/bin/udevd ] && DEFAULT_SERVICES="eudev"
+  [ -x /usr/lib/systemd/systemd-udevd ] && DEFAULT_SERVICES="udev"
 
-  for FILE in `ls /etc/rc.d/* | sort`; do
-    FILE=`basename "${FILE}"`
+  ENABLED_SERVICES="${DEFAULT_SERVICES} ${SERVICES}"
 
-    STATUS1="disabled"; COLOR1="${MAGENTA}"
-    STATUS2="n/a"; COLOR2="${MAGENTA}"
+  case "$1" in
+    all) SERVICES=`find /etc/rc.d/* -type f -exec basename {} \; | tr '\n' ' '` ;;
+    "") SERVICES="${ENABLED_SERVICES}" ;;
+    *) SERVICES="$@" ;;
+  esac
 
-    for SERVICE in ${SERVICES}; do
-      if [ "${SERVICE}" = "${FILE}" ]; then
+  SERVICES=`echo "${SERVICES}" | tr ' ' '\n' | grep -v '^$' | sort | tr '\n' ' '`
+
+  STATUS=0
+  for SERVICE in ${SERVICES}; do
+    if [ -e /etc/rc.d/"${SERVICE}" ]; then
+      STATUS1="disabled"; COLOR1="${MAGENTA}"
+      STATUS2="n/a"; COLOR2="${MAGENTA}"
+
+      if echo "${ENABLED_SERVICES}" | tr ' ' '\n' | grep -Fxq "${SERVICE}"; then
         STATUS1="enabled"; COLOR1="${BLUE}"
 
-        if grep rc_run /etc/rc.d/"${FILE}" | grep status 1>/dev/null 2>/dev/null; then
-          /etc/rc.d/"${FILE}" status 1>/dev/null 2>/dev/null
+        # FIXME: find a better way to determine if the rc script provides a 'status' function
+        if grep rc_run /etc/rc.d/"${SERVICE}" | grep -Fq status; then
+          /etc/rc.d/"${SERVICE}" status 1>/dev/null 2>/dev/null
+
           if [ $? -eq 0 ]; then
             STATUS2="started"; COLOR2="${GREEN}"
           else
+            STATUS=$?
             STATUS2="stopped"; COLOR2="${RED}"
           fi
         fi
       fi
-    done
 
-    if [ $# -eq 0 ]; then
-      if [ "${STATUS2}" != "n/a" ]; then
-        printf "%b%-*.*s%b%s%b\n" "${GREY}" 10 10 "${FILE}" "${COLOR2}" "${STATUS2}" "${GREY}"
-      fi
+      case "$1" in
+        all)
+          printf "%b%-*.*s%b%-*.*s%b%s%b\n" "${GREY}" 10 10 "${SERVICE}" "${COLOR1}" 9 9 "${STATUS1}" "${COLOR2}" "${STATUS2}" "${GREY}"
+          ;;
+        "")
+          if [ "${STATUS2}" != "n/a" ]; then
+            printf "%b%-*.*s%b%s%b\n" "${GREY}" 10 10 "${SERVICE}" "${COLOR2}" "${STATUS2}" "${GREY}"
+          fi
+          ;;
+        *)
+          printf "%b%s %b%s %b%s %b\n" "${GREY}" "${SERVICE}" "${COLOR1}" "${STATUS1}" "${COLOR2}" "${STATUS2}" "${GREY}"
+
+          if [ "${STATUS2}" != "n/a" ]; then
+            /etc/rc.d/"${SERVICE}" status
+          fi
+          ;;
+      esac
     else
-      if [ "$1" = "all" ]; then
-        printf "%b%-*.*s%b%-*.*s%b%s%b\n" "${GREY}" 10 10 "${FILE}" "${COLOR1}" 9 9 "${STATUS1}" "${COLOR2}" "${STATUS2}" "${GREY}"
-      fi
-
-      if [ "$1" = "${FILE}" ]; then
-        printf "%b%s %b%s %b%s %b\n" "${GREY}" "${FILE}" "${COLOR1}" "${STATUS1}" "${COLOR2}" "${STATUS2}" "${GREY}"
-
-        if [ "${STATUS2}" != "n/a" ]; then
-          /etc/rc.d/"${FILE}" status
-          return $?
-        else
-          return 0
-        fi
-      fi
+      echo "error: /etc/rc.d/${SERVICE} doesn't exist"
     fi
   done
-
-  if [ $# -eq 1 -a "$1" != "all" ]; then
-    echo "error: /etc/rc.d/$1 doesn't exist"
-    return 1
-  fi
-
-  return 0
+  return $STATUS
 }
 
 rc_run() {
@@ -99,31 +97,37 @@ rc_run() {
     return 1
   fi
 
-  if [ $# -ne 2 ]; then
+  if [ $# -lt 2 ]; then
     rc_usage
     return 1
   fi
 
-  if [ ! -e /etc/rc.d/"$2" ]; then
-    echo "error: /etc/rc.d/$2 doesn't exist"
-    return 1
-  fi
+  ACTION="$1"
+  shift
 
-  /etc/rc.d/"$2" "$1"
-  return $?
+  STATUS=0
+  while [ $# -ne 0 ]; do
+    if [ -e /etc/rc.d/"$1" ]; then
+      /etc/rc.d/"$1" "$ACTION" || STATUS=$?
+    else
+      echo "error: /etc/rc.d/$1 doesn't exist"
+      STATUS=1
+    fi
+
+    shift
+  done
+  return $STATUS
 }
 
 rc_usage() {
-  echo "usage: `basename $0` status [all]"
-  echo "       `basename $0` status service"
-  echo "       `basename $0` {start|stop|restart|reload|display} service"
+  echo "usage: `basename $0` status [all|service...]"
+  echo "       `basename $0` {start|stop|restart|reload|display} service..."
 
   return 1
 }
 
 case "$1" in
   status)
-    shift
     rc_status $@
     exit $?
     ;;
