must be root to search for libraries

diff --git a/tools/searchlibrary b/tools/searchlibrary
--- a/tools/searchlibrary
+++ b/tools/searchlibrary
@@ -2,6 +2,11 @@
 
 export LC_ALL=C
 
+if [ $(id -u) -ne 0 ]; then
+  echo "error: this script should be run as root"
+  exit 1
+fi
+
 searchfile() {
   LIBRARY=$(readelf -d "$2" 2>/dev/null | grep library | grep "$1" | cut -d ':' -f 2 | tr -d '[]' | tr -d ' ')
 
