clean and rework the scripts to allow 2 vm (for systemd and initsystem)

diff --git a/tools/vm-upgrade b/tools/vm-upgrade
--- a/tools/vm-upgrade
+++ b/tools/vm-upgrade
@@ -1,33 +1,49 @@
 #!/bin/bash
 
-set -u
+# todo: avoid harcoded paths
 
 if [ $(id -u) -ne 0 ]; then
   echo "error: this script should be run as root"
   exit 1
 fi
 
-################################################################################
-# vbox #########################################################################
-################################################################################
-
-# sudo qemu-nbd -c /dev/nbd0 "/home/valr/document/system/vbox/archlinux/archlinux.vdi"
-# sudo partx -a /dev/nbd0
-# sudo mount -t ext4 /dev/nbd0p2 /mnt
-# sudo mount -t vfat /dev/nbd0p1 /mnt/boot
-# sudo mount -t ext4 /dev/nbd0p3 /mnt/var
-# sudo chroot /mnt /bin/bash
-# sudo umount /mnt/var
-# sudo umount /mnt/boot
-# sudo umount /mnt
-# sudo qemu-nbd -d /dev/nbd0
-
 DEVICE="/dev/nbd0"
 PARTITION_ROOT="/dev/nbd0p2"
 PARTITION_BOOT="/dev/nbd0p1"
-PARTITION_VAR="/dev/nbd0p3"
 ROOT="/mnt"
-IMAGE="/home/valr/document/system/vbox/archlinux/archlinux.vdi"
+
+PACKAGES_SYSTEMD="
+../initsystem/busybox/busybox-1.27.1-1-x86_64.pkg.tar.xz
+../initsystem/initramfs/initramfs-1.2.0-1-any.pkg.tar.xz
+../initsystem/initsystem/initsystem-1.2.0-1-x86_64.pkg.tar.xz
+"
+
+PACKAGES_INITSYSTEM="
+${PACKAGES_SYSTEMD}
+../initsystem/eudev/eudev-3.2.2-1-x86_64.pkg.tar.xz
+../initsystem/opentmpfiles/opentmpfiles-0.1.3-1-any.pkg.tar.xz
+../initsystem/systemd-minimal/systemd-minimal-234.11-1-any.pkg.tar.xz
+"
+
+case "$1" in
+  initsystem)
+    IMAGE="/home/valr/document/system/vbox/archlinux-$1/archlinux-$1.vdi"
+    PACKAGES="${PACKAGES_INITSYSTEM}"
+    ;;
+  systemd)
+    IMAGE="/home/valr/document/system/vbox/archlinux-$1/archlinux-$1.vdi"
+    PACKAGES="${PACKAGES_SYSTEMD}"
+    ;;
+  *)
+    echo "usage: $(basename $0) initsystem|systemd"
+    exit 1
+    ;;
+esac
+
+if [ ! -e "${IMAGE}" ]; then
+  echo "error: the image ${IMAGE} does not exist"
+  exit 1
+fi
 
 wait_device() {
   for i in $(seq $2); do
@@ -46,7 +62,6 @@ partx -a "${DEVICE}"
 
 wait_device "${PARTITION_ROOT}" 40 && mount -t ext4 "${PARTITION_ROOT}" "${ROOT}"
 wait_device "${PARTITION_BOOT}" 40 && mount -t vfat "${PARTITION_BOOT}" "${ROOT}"/boot
-wait_device "${PARTITION_VAR}"  40 && mount -t ext4 "${PARTITION_VAR}"  "${ROOT}"/var
 
 pacman -U \
   --dbpath   "${ROOT}"/var/lib/pacman/ \
@@ -54,21 +69,16 @@ pacman -U \
   --cachedir "${ROOT}"/var/cache/pacman/pkg/ \
   --config   "${ROOT}"/etc/pacman.conf \
   --gpgdir   "${ROOT}"/etc/pacman.d/gnupg/ \
-  --hookdir  "${ROOT}"/var/empty \
+  --hookdir  "${ROOT}"/usr/share/libalpm/hooks/ \
   --logfile  "${ROOT}"/var/log/pacman.log \
   --noconfirm \
   --noscriptlet \
-  ../initsystem/busybox/busybox-1.27.1-1-x86_64.pkg.tar.xz \
-  ../initsystem/initramfs/initramfs-1.2.0-1-any.pkg.tar.xz \
-  ../initsystem/initsystem/initsystem-1.2.0-1-x86_64.pkg.tar.xz
+  ${PACKAGES}
 
-cp -f ../initsystem/busybox/busybox-1.27.1-1-x86_64.pkg.tar.xz "${ROOT}"/root
-cp -f ../initsystem/initramfs/initramfs-1.2.0-1-any.pkg.tar.xz "${ROOT}"/root
-cp -f ../initsystem/initsystem/initsystem-1.2.0-1-x86_64.pkg.tar.xz "${ROOT}"/root
+cp -f ${PACKAGES} "${ROOT}"/root
 
 sync
 
-umount "${ROOT}"/var
 umount "${ROOT}"/boot
 umount "${ROOT}"
 
@@ -76,39 +86,11 @@ qemu-nbd -d "${DEVICE}"
 
 exit 0
 
-################################################################################
-# qemu #########################################################################
-################################################################################
-
-# sudo qemu-nbd -P 1 -c "/dev/nbd0" "/home/valr/document/system/qemu/archlinux/archlinux.img"
-# sudo mount -t ext4 -o rw /dev/nbd0 /mnt
-# ...
+# sudo qemu-nbd -c /dev/nbd0 "/home/valr/document/system/vbox/archlinux/archlinux.vdi"
+# sudo partx -a /dev/nbd0
+# sudo mount -t ext4 /dev/nbd0p2 /mnt
+# sudo mount -t vfat /dev/nbd0p1 /mnt/boot
+# sudo chroot /mnt /bin/bash
+# sudo umount /mnt/boot
 # sudo umount /mnt
 # sudo qemu-nbd -d /dev/nbd0
-
-DEVICE="/dev/nbd0"
-ROOT="/mnt"
-IMAGE="/home/valr/document/system/qemu/archlinux/archlinux.img"
-
-qemu-nbd -P 1 -c "${DEVICE}" "${IMAGE}"
-mount -t ext4 "${DEVICE}" "${ROOT}"
-
-pacman -U \
-  --root     "${ROOT}" \
-  --config   "${ROOT}"/etc/pacman.conf \
-  --gpgdir   "${ROOT}"/etc/pacman.d/gnupg \
-  --dbpath   "${ROOT}"/var/lib/pacman \
-  --cachedir "${ROOT}"/var/cache/pacman/pkg \
-  --logfile  "${ROOT}"/var/log/pacman.log \
-  --noscriptlet --noconfirm \
-  ../busybox/busybox-1.24.2-2-x86_64.pkg.tar.xz \
-  ../initramfs/initramfs-1.1.0-1-any.pkg.tar.xz \
-  ../initsystem/initsystem-1.0.0-1-x86_64.pkg.tar.xz \
-  ../services/services-1.0.0-1-any.pkg.tar.xz
-
-sync
-
-umount "${ROOT}"
-qemu-nbd -d "${DEVICE}"
-
-exit 0
