clean and improve a bit the testing tools

diff --git a/tools/vm-upgrade b/tools/vm-upgrade
--- a/tools/vm-upgrade
+++ b/tools/vm-upgrade
@@ -1,16 +1,11 @@
 #!/bin/bash
 
-# todo: avoid harcoded paths
+# TODO: avoid harcoded paths
 
 if [ $(id -u) -ne 0 ]; then
   echo "error: this script should be run as root"
   exit 1
 fi
-
-DEVICE="/dev/nbd0"
-PARTITION_ROOT="/dev/nbd0p2"
-PARTITION_BOOT="/dev/nbd0p1"
-ROOT="/mnt"
 
 PACKAGES_SYSTEMD="
 ../initsystem/busybox/busybox-1.28.1-1-x86_64.pkg.tar.xz
@@ -44,13 +39,15 @@ case "$1" in
     ;;
 esac
 
+for FILE in "${IMAGE}" ${PACKAGES}; do
+  if [ ! -e "${FILE}" ]; then
+    echo "error: the file ${FILE} does not exist"
+    exit 1
+  fi
+done
+
 if ps ax | grep [a]rchlinux-"$1" &>/dev/null; then
   echo "error: the virtual machine is running"
-  exit 1
-fi
-
-if [ ! -e "${IMAGE}" ]; then
-  echo "error: the image ${IMAGE} does not exist"
   exit 1
 fi
 
@@ -65,6 +62,11 @@ wait_device() {
 
   return 1
 }
+
+DEVICE="/dev/nbd0"
+PARTITION_ROOT="/dev/nbd0p2"
+PARTITION_BOOT="/dev/nbd0p1"
+ROOT="/mnt"
 
 qemu-nbd -c "${DEVICE}" "${IMAGE}"
 partx -a "${DEVICE}"
